# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_pymbn_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from .base_classes import Setup


class QTGUI(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(789, 743)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 670, 771, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.get_parameters)
        self.horizontalLayout_2.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.exit_button_clicked)
        self.horizontalLayout_2.addWidget(self.pushButton_2)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 371, 628))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mbn_construction_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.mbn_construction_box.setObjectName("mbn_construction_box")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.mbn_construction_box)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtWidgets.QLabel(self.mbn_construction_box)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)

        self.comboBox_7 = QtWidgets.QComboBox(self.mbn_construction_box)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.currentIndexChanged.connect(self.get_mbn_construction_method_value)

        self.horizontalLayout_28.addWidget(self.comboBox_7)

        self.verticalLayout.addWidget(self.mbn_construction_box)
        self.alpha_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.alpha_box.setObjectName("alpha_box")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.alpha_box)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_23 = QtWidgets.QLabel(self.alpha_box)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_26.addWidget(self.label_23)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)

        self.lineEdit_12 = QtWidgets.QLineEdit(self.alpha_box)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.textChanged.connect(self.get_alpha_value)
        self.horizontalLayout_26.addWidget(self.lineEdit_12)

        self.verticalLayout.addWidget(self.alpha_box)
        self.theta_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.theta_box.setObjectName("theta_box")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.theta_box)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.theta_box)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)

        self.lineEdit_11 = QtWidgets.QLineEdit(self.theta_box)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.textChanged.connect(self.get_theta_value)
        self.horizontalLayout_25.addWidget(self.lineEdit_11)

        self.verticalLayout.addWidget(self.theta_box)
        self.threshold_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.threshold_box.setObjectName("threshold_box")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.threshold_box)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.threshold_box)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)

        self.lineEdit_10 = QtWidgets.QLineEdit(self.threshold_box)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.textChanged.connect(self.get_threshold_value)
        self.horizontalLayout_24.addWidget(self.lineEdit_10)

        self.verticalLayout.addWidget(self.threshold_box)
        self.weights_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.weights_box.setObjectName("weights_box")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.weights_box)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_20 = QtWidgets.QLabel(self.weights_box)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_23.addWidget(self.label_20)

        self.comboBox_2 = QtWidgets.QComboBox(self.weights_box)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.currentIndexChanged.connect(self.get_weights_value)

        self.horizontalLayout_23.addWidget(self.comboBox_2)
        self.verticalLayout.addWidget(self.weights_box)
        self.correction_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.correction_box.setObjectName("correction_box")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.correction_box)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.correction_box)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)

        self.comboBox_3 = QtWidgets.QComboBox(self.correction_box)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.currentIndexChanged.connect(self.get_correction_type_value)

        self.horizontalLayout_22.addWidget(self.comboBox_3)
        self.verticalLayout.addWidget(self.correction_box)
        self.sampling_type_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.sampling_type_box.setObjectName("sampling_type_box")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.sampling_type_box)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.sampling_type_box)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)

        self.comboBox_4 = QtWidgets.QComboBox(self.sampling_type_box)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.currentIndexChanged.connect(self.get_sampling_type_value)

        self.horizontalLayout_16.addWidget(self.comboBox_4)
        self.verticalLayout.addWidget(self.sampling_type_box)
        self.n_samples_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.n_samples_box.setObjectName("n_samples_box")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.n_samples_box)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.n_samples_box)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)

        self.lineEdit_9 = QtWidgets.QLineEdit(self.n_samples_box)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.textChanged.connect(self.get_n_samples_value)

        self.horizontalLayout_21.addWidget(self.lineEdit_9)
        self.verticalLayout.addWidget(self.n_samples_box)
        self.criteria_representation_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.criteria_representation_box.setObjectName("criteria_representation_box")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.criteria_representation_box)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.criteria_representation_box)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)

        self.comboBox_5 = QtWidgets.QComboBox(self.criteria_representation_box)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.currentIndexChanged.connect(self.get_criteria_representation_value)

        self.horizontalLayout_15.addWidget(self.comboBox_5)
        self.verticalLayout.addWidget(self.criteria_representation_box)
        self.data_balance_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.data_balance_box.setObjectName("data_balance_box")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.data_balance_box)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.data_balance_box)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)

        self.comboBox_6 = QtWidgets.QComboBox(self.data_balance_box)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.currentIndexChanged.connect(self.get_data_balance_value)

        self.horizontalLayout_17.addWidget(self.comboBox_6)
        self.verticalLayout.addWidget(self.data_balance_box)
        self.sample_measures_box = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.sample_measures_box.setObjectName("sample_measures_box")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.sample_measures_box)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")

        self.checkBox = QtWidgets.QCheckBox(self.sample_measures_box)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setChecked(False)
        self.checkBox.stateChanged.connect(self.sample_measures_is_checked)

        self.horizontalLayout_20.addWidget(self.checkBox)
        self.label_17 = QtWidgets.QLabel(self.sample_measures_box)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem4)

        self.lineEdit_8 = QtWidgets.QLineEdit(self.sample_measures_box)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.textChanged.connect(self.get_n_sample_measures)

        self.horizontalLayout_20.addWidget(self.lineEdit_8)

        self.verticalLayout.addWidget(self.sample_measures_box)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(400, 40, 381, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.checkBox_6 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_6.setChecked(False)
        self.checkBox_6.stateChanged.connect(self.plot_3d_is_checked)
        self.verticalLayout_4.addWidget(self.checkBox_6)

        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.stateChanged.connect(self.plot_3d_interactive_is_checked)
        self.verticalLayout_4.addWidget(self.checkBox_7)

        self.verticalLayout_2.addLayout(self.verticalLayout_4)

        self.brain_type_box = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.brain_type_box.setObjectName("brain_type_box")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.brain_type_box)

        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.brain_type_box)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)

        self.comboBox = QtWidgets.QComboBox(self.brain_type_box)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setEnabled(False)
        self.comboBox.currentIndexChanged.connect(self.get_brain_type_value)

        self.horizontalLayout_18.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.brain_type_box)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(400, 200, 381, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.checkBox_8 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.stateChanged.connect(self.get_plot_heatmap_value)
        self.verticalLayout_5.addWidget(self.checkBox_8)

        self.checkBox_9 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_9.setChecked(True)
        self.checkBox_9.stateChanged.connect(self.get_plot_circle_value)
        self.verticalLayout_5.addWidget(self.checkBox_9)

        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.Output_format_box = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        self.Output_format_box.setObjectName("Output_format_box")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.Output_format_box)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.Output_format_box)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)

        self.comboBox_8 = QtWidgets.QComboBox(self.Output_format_box)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.currentIndexChanged.connect(self.get_output_format_value)

        self.horizontalLayout_19.addWidget(self.comboBox_8)
        self.verticalLayout_3.addWidget(self.Output_format_box)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 0, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "MS-scheme parameters:"))
        self.pushButton.setText(_translate("MainWindow", "Set parameters"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
        self.label_27.setText(_translate("MainWindow", "MBN construction method: "))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "ms-scheme"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "conventional"))
        self.label_23.setText(_translate("MainWindow", "alpha:"))
        self.lineEdit_12.setText(_translate("MainWindow", "0.05"))
        self.label_22.setText(_translate("MainWindow", "theta:"))
        self.lineEdit_11.setText(_translate("MainWindow", "0.95"))
        self.label_21.setText(_translate("MainWindow", "threshold:"))
        self.lineEdit_10.setText(_translate("MainWindow", "0.3"))
        self.label_20.setText(_translate("MainWindow", "weights:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Pearson correlation"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Spearman correlation"))
        self.label_19.setText(_translate("MainWindow", "correction type:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "FDR (B&H-1995)"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Bonferroni"))
        self.label_13.setText(_translate("MainWindow", "sampling type:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "bootstrap"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "subsample"))
        self.label_18.setText(_translate("MainWindow", "number of samples:"))
        self.lineEdit_9.setText(_translate("MainWindow", "2000"))
        self.label_12.setText(_translate("MainWindow", "criteria representation:"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "mean"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "mode"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "median"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "geodesic"))
        self.label_14.setText(_translate("MainWindow", "data balance:"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "not balanced"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "ADASYM"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "downsample"))
        self.checkBox.setText(_translate("MainWindow", "sample Measures"))
        self.label_17.setText(_translate("MainWindow", "(number measures)"))
        self.lineEdit_8.setText(_translate("MainWindow", "30"))
        self.label_3.setText(_translate("MainWindow", "3D brain plot:"))
        self.checkBox_6.setText(_translate("MainWindow", "Plot 3D"))
        self.checkBox_7.setText(_translate("MainWindow", "3D interactive"))
        self.label_15.setText(_translate("MainWindow", "brain type:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "human"))
        self.comboBox.setItemText(1, _translate("MainWindow", "rat/mice"))
        self.label_16.setText(_translate("MainWindow", "network plots:"))
        self.checkBox_8.setText(_translate("MainWindow", "plot heatmap"))
        self.checkBox_9.setText(_translate("MainWindow", "plot circle"))
        self.label_26.setText(_translate("MainWindow", "output format: "))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "png"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "jpg"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "svg"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "pdf"))
        self.label_4.setText(_translate("MainWindow", "Plotting options:"))

    def exit_button_clicked(self):
        QtWidgets.QApplication.quit()

    def get_parameters(self):
        self.setup = Setup(
            mbn_method=self.get_mbn_construction_method_value(),
            alpha=self.get_alpha_value(),
            theta=self.get_theta_value(),
            threshold=self.get_threshold_value(),
            weights=self.get_weights_value(),
            correction_type=self.get_correction_type_value(),
            sampling_type=self.get_sampling_type_value(),
            n_samples=self.get_n_samples_value(),
            criteria_representation=self.get_criteria_representation_value(),
            data_balance=self.get_data_balance_value(),
            n_samples_measures=self.get_n_sample_measures(),
            plot_3d=self.plot_3d_is_checked,
            interactive=self.plot_3d_interactive_is_checked(),
            brain_type=self.get_brain_type_value(),
            plot_heatmap=self.get_plot_heatmap_value(),
            plot_circle=self.get_plot_circle_value(),
            output_format=self.get_output_format_value(),
            probability_treshold=self.get_probability_treshold(),
            seed=13,
        )
        # close window
        self.MainWindow.close()

    @staticmethod
    def get_probability_treshold():
        return 0.95

    def get_mbn_construction_method_value(self):
        return self.comboBox_7.currentText()

    def get_alpha_value(self):
        return self.lineEdit_12.text()

    def get_theta_value(self):
        return self.lineEdit_11.text()

    def get_threshold_value(self):
        return self.lineEdit_10.text()

    def get_weights_value(self):
        return self.comboBox_2.currentText()

    def get_correction_type_value(self):
        return self.comboBox_3.currentText()

    def get_sampling_type_value(self):
        return self.comboBox_4.currentText()

    def get_n_samples_value(self):
        return self.lineEdit_9.text()

    def get_criteria_representation_value(self):
        return self.comboBox_5.currentText()

    def get_data_balance_value(self):
        return self.comboBox_6.currentText()

    def get_n_sample_measures(self):
        return self.lineEdit_8.text()

    def sample_measures_is_checked(self):
        if self.checkBox.isChecked():
            self.lineEdit_8.setEnabled(True)
        else:
            self.lineEdit_8.setEnabled(False)

    def plot_3d_is_checked(self):
        # Slot function to handle changes in the "Plot 3D" checkbox state
        if self.checkBox_6.isChecked():
            # If "Plot 3D" is checked, enable the "3D interactive" checkbox
            self.checkBox_7.setEnabled(True)
            self.comboBox.setEnabled(True)
            return True
        else:
            # If "Plot 3D" is not checked, disable the "3D interactive" checkbox
            self.checkBox_7.setEnabled(False)
            self.comboBox.setEnabled(False)
            return False

    def plot_3d_interactive_is_checked(self):
        if self.checkBox_7.isChecked():
            return True
        else:
            return False

    def get_brain_type_value(self):
        return self.comboBox.currentText()

    def get_plot_heatmap_value(self):
        return self.checkBox_8.isChecked()

    def get_plot_circle_value(self):
        return self.checkBox_9.isChecked()

    def get_output_format_value(self):
        return self.comboBox_8.currentText()

    @staticmethod
    def start_gui():
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = QTGUI()
        ui.setupUi(MainWindow)
        MainWindow.show()
        app.exec_()
        return ui


# if __name__ == "__main__":
# import sys

# app = QtWidgets.QApplication(sys.argv)
# MainWindow = QtWidgets.QMainWindow()
# ui = QTGUI()
# ui.setupUi(MainWindow)
# MainWindow.show()
# sys.exit(app.exec_())
